import type {
  CoreRole,
  Membership,
  PermissionCategory,
  PermissionKey,
  StaffTemplateKey,
} from "./types";

export const permissionCatalog: Record<
  PermissionCategory,
  { label: string; permissions: { key: PermissionKey; label: string }[] }
> = {
  dashboard: {
    label: "Dashboard",
    permissions: [
      { key: "dashboard.view_owner", label: "View owner dashboard" },
      { key: "dashboard.view_manager", label: "View manager dashboard" },
      { key: "dashboard.view_staff", label: "View staff dashboard" },
      { key: "dashboard.view_business_health", label: "View business health" },
      { key: "dashboard.view_business_insights", label: "View business insights" },
      {
        key: "dashboard.view_sensitive_financial_summaries",
        label: "View sensitive financial summaries",
      },
    ],
  },
  sales: {
    label: "Sales",
    permissions: [
      { key: "sales.view", label: "View sales" },
      { key: "sales.create", label: "Create sales" },
      { key: "sales.edit_draft", label: "Edit draft sales" },
      { key: "sales.approve_discounts", label: "Approve discounts" },
      { key: "sales.issue_invoices", label: "Issue invoices" },
      { key: "sales.receive_payments", label: "Receive payments" },
      { key: "sales.cancel_invoices", label: "Cancel invoices" },
      { key: "sales.view_customer_balances", label: "View customer balances" },
    ],
  },
  purchases: {
    label: "Purchases",
    permissions: [
      { key: "purchases.view", label: "View purchases" },
      { key: "purchases.create", label: "Create purchases" },
      { key: "purchases.approve", label: "Approve purchases" },
      { key: "purchases.receive_stock", label: "Receive stock" },
      { key: "purchases.record_supplier_invoices", label: "Record supplier invoices" },
      { key: "purchases.record_supplier_payments", label: "Record supplier payments" },
      { key: "purchases.view_suppliers", label: "View suppliers" },
      { key: "purchases.create_suppliers", label: "Create suppliers" },
      { key: "purchases.edit_suppliers", label: "Edit suppliers" },
      { key: "purchases.approve_suppliers", label: "Approve suppliers" },
      { key: "purchases.view_supplier_prices", label: "View supplier prices" },
      { key: "purchases.manage_supplier_prices", label: "Manage supplier prices" },
      { key: "purchases.view_supplier_documents", label: "View supplier documents" },
      { key: "purchases.create_requisitions", label: "Create requisitions" },
      { key: "purchases.approve_requisitions", label: "Approve requisitions" },
      { key: "purchases.create_purchase_orders", label: "Create purchase orders" },
      { key: "purchases.edit_draft_purchase_orders", label: "Edit draft purchase orders" },
      { key: "purchases.approve_purchase_orders", label: "Approve purchase orders" },
      { key: "purchases.send_purchase_orders", label: "Send purchase orders" },
      { key: "purchases.inspect_goods", label: "Inspect goods" },
      { key: "purchases.approve_grns", label: "Approve GRNs" },
      { key: "purchases.post_grns", label: "Post GRNs" },
      { key: "purchases.approve_supplier_bills", label: "Approve supplier bills" },
      { key: "purchases.override_match_exceptions", label: "Override match exceptions" },
      { key: "purchases.create_supplier_returns", label: "Create supplier returns" },
      { key: "purchases.approve_supplier_returns", label: "Approve supplier returns" },
      { key: "purchases.approve_supplier_payments", label: "Approve supplier payments" },
      { key: "purchases.view_supplier_balances", label: "View supplier balances" },
      { key: "purchases.view_creditor_ageing", label: "View creditor ageing" },
      { key: "purchases.export_purchase_data", label: "Export purchase data" },
      { key: "purchases.import_supplier_data", label: "Import supplier data" },
      { key: "purchases.reverse_purchase_transactions", label: "Reverse purchase transactions" },
    ],
  },
  inventory: {
    label: "Inventory",
    permissions: [
      { key: "inventory.view_stock", label: "View stock" },
      { key: "inventory.add_products", label: "Add products" },
      { key: "inventory.edit_products", label: "Edit products" },
      { key: "inventory.adjust_stock", label: "Adjust stock" },
      { key: "inventory.perform_stock_counts", label: "Perform stock counts" },
      { key: "inventory.view_buying_prices", label: "View buying prices" },
      { key: "inventory.view_selling_prices", label: "View selling prices" },
      { key: "inventory.transfer_stock", label: "Transfer stock" },
      { key: "inventory.archive_products", label: "Archive products" },
      { key: "inventory.view_inventory_value", label: "View inventory value" },
      { key: "inventory.enter_opening_stock", label: "Enter opening stock" },
      { key: "inventory.receive_transfers", label: "Receive transfers" },
      { key: "inventory.approve_adjustments", label: "Approve stock adjustments" },
      { key: "inventory.approve_stock_counts", label: "Approve stock counts" },
      { key: "inventory.view_batches", label: "View batches" },
      { key: "inventory.dispose_expired_stock", label: "Dispose expired stock" },
      { key: "inventory.manage_serial_numbers", label: "Manage serial numbers" },
      { key: "inventory.export_inventory", label: "Export inventory" },
      { key: "inventory.revalue_stock", label: "Revalue stock" },
      { key: "inventory.close_inventory_periods", label: "Close inventory periods" },
    ],
  },
  finance: {
    label: "Finance",
    permissions: [
      { key: "finance.view_cashbook", label: "View cashbook" },
      { key: "finance.view_financial_accounts", label: "View financial accounts" },
      { key: "finance.create_financial_accounts", label: "Create financial accounts" },
      { key: "finance.edit_financial_accounts", label: "Edit financial accounts" },
      { key: "finance.view_full_account_details", label: "View full account details" },
      { key: "finance.view_account_balances", label: "View account balances" },
      { key: "finance.create_receipts", label: "Create receipts" },
      { key: "finance.create_payments", label: "Create payments" },
      { key: "finance.approve_payments", label: "Approve payments" },
      { key: "finance.record_expenses", label: "Record expenses" },
      { key: "finance.approve_expenses", label: "Approve expenses" },
      { key: "finance.submit_expense_claims", label: "Submit expense claims" },
      { key: "finance.approve_expense_claims", label: "Approve expense claims" },
      { key: "finance.manage_petty_cash", label: "Manage petty cash" },
      { key: "finance.reconcile_petty_cash", label: "Reconcile petty cash" },
      { key: "finance.create_bank_deposits", label: "Create bank deposits" },
      { key: "finance.verify_bank_deposits", label: "Verify bank deposits" },
      { key: "finance.create_withdrawals", label: "Create withdrawals" },
      { key: "finance.create_transfers", label: "Create transfers" },
      { key: "finance.approve_transfers", label: "Approve transfers" },
      { key: "finance.confirm_transfers", label: "Confirm transfers" },
      { key: "finance.manage_cheques", label: "Manage cheques" },
      { key: "finance.view_profit", label: "View profit" },
      { key: "finance.view_balance_sheet", label: "View balance sheet" },
      { key: "finance.view_cash_flow", label: "View cash flow" },
      { key: "finance.view_owner_transactions", label: "View owner transactions" },
      { key: "finance.record_owner_transactions", label: "Record owner transactions" },
      { key: "finance.approve_owner_transactions", label: "Approve owner transactions" },
      { key: "finance.issue_staff_advances", label: "Issue staff advances" },
      { key: "finance.approve_staff_advances", label: "Approve staff advances" },
      { key: "finance.review_advance_surrender", label: "Review advance surrender" },
      { key: "finance.view_driver_cash", label: "View driver cash" },
      { key: "finance.record_cash_handover", label: "Record cash handover" },
      { key: "finance.import_statements", label: "Import statements" },
      { key: "finance.reconcile_bank_accounts", label: "Reconcile bank accounts" },
      { key: "finance.reconcile_mobile_money_accounts", label: "Reconcile mobile-money accounts" },
      { key: "finance.approve_reconciliations", label: "Approve reconciliations" },
      { key: "finance.reopen_reconciliations", label: "Reopen reconciliations" },
      { key: "finance.record_cash_counts", label: "Record cash counts" },
      { key: "finance.approve_cash_variances", label: "Approve cash variances" },
      { key: "finance.view_treasury_reports", label: "View treasury reports" },
      { key: "finance.export_treasury_data", label: "Export treasury data" },
      { key: "finance.reverse_treasury_transactions", label: "Reverse treasury transactions" },
      { key: "finance.close_accounting_periods", label: "Close accounting periods" },
      { key: "finance.export_financial_reports", label: "Export financial reports" },
    ],
  },
  distribution: {
    label: "Distribution",
    permissions: [
      { key: "distribution.view_deliveries", label: "View deliveries" },
      { key: "distribution.create_deliveries", label: "Create deliveries" },
      { key: "distribution.edit_draft_delivery_runs", label: "Edit draft delivery runs" },
      { key: "distribution.approve_delivery_runs", label: "Approve delivery runs" },
      { key: "distribution.assign_vehicles", label: "Assign vehicles" },
      { key: "distribution.assign_drivers", label: "Assign drivers" },
      { key: "distribution.create_loading_sheets", label: "Create loading sheets" },
      { key: "distribution.pick_stock", label: "Pick stock" },
      { key: "distribution.verify_loading", label: "Verify loading" },
      { key: "distribution.dispatch_vehicles", label: "Dispatch vehicles" },
      { key: "distribution.view_assigned_runs", label: "View assigned runs" },
      { key: "distribution.confirm_arrival", label: "Confirm arrival" },
      { key: "distribution.confirm_deliveries", label: "Confirm deliveries" },
      { key: "distribution.record_partial_delivery", label: "Record partial delivery" },
      { key: "distribution.record_failed_delivery", label: "Record failed delivery" },
      { key: "distribution.capture_proof_of_delivery", label: "Capture proof of delivery" },
      { key: "distribution.record_collections", label: "Record collections" },
      { key: "distribution.record_returns", label: "Record returns" },
      { key: "distribution.record_crate_movements", label: "Record crate movements" },
      { key: "distribution.record_route_expenses", label: "Record route expenses" },
      { key: "distribution.reconcile_vehicle_stock", label: "Reconcile vehicle stock" },
      { key: "distribution.approve_stock_variances", label: "Approve stock variances" },
      { key: "distribution.reconcile_route_collections", label: "Reconcile route collections" },
      { key: "distribution.approve_cash_variances", label: "Approve cash variances" },
      { key: "distribution.close_delivery_runs", label: "Close delivery runs" },
      { key: "distribution.reopen_delivery_runs", label: "Reopen delivery runs" },
      { key: "distribution.view_routes", label: "View routes" },
      { key: "distribution.view_distribution_reports", label: "View distribution reports" },
      { key: "distribution.export_distribution_data", label: "Export distribution data" },
    ],
  },
  administration: {
    label: "Administration",
    permissions: [
      { key: "administration.manage_users", label: "Manage users" },
      { key: "administration.manage_permissions", label: "Manage permissions" },
      { key: "administration.manage_business_settings", label: "Manage business settings" },
      { key: "administration.view_audit_logs", label: "View audit logs" },
      { key: "administration.export_data", label: "Export data" },
      { key: "administration.delete_draft_records", label: "Delete draft records" },
      { key: "administration.approve_sensitive_actions", label: "Approve sensitive actions" },
    ],
  },
};

export const allPermissions = Object.values(permissionCatalog).flatMap((category) =>
  category.permissions.map((permission) => permission.key),
);

export const roleDefaults: Record<CoreRole, PermissionKey[]> = {
  owner: allPermissions,
  manager: [
    "dashboard.view_manager",
    "dashboard.view_business_health",
    "finance.view_cashbook",
    "finance.view_financial_accounts",
    "finance.view_account_balances",
    "finance.create_receipts",
    "finance.create_payments",
    "finance.approve_payments",
    "finance.record_expenses",
    "finance.approve_expenses",
    "finance.approve_expense_claims",
    "finance.manage_petty_cash",
    "finance.reconcile_petty_cash",
    "finance.create_bank_deposits",
    "finance.verify_bank_deposits",
    "finance.create_withdrawals",
    "finance.create_transfers",
    "finance.approve_transfers",
    "finance.confirm_transfers",
    "finance.manage_cheques",
    "finance.view_cash_flow",
    "finance.issue_staff_advances",
    "finance.approve_staff_advances",
    "finance.review_advance_surrender",
    "finance.view_driver_cash",
    "finance.record_cash_handover",
    "finance.import_statements",
    "finance.reconcile_bank_accounts",
    "finance.reconcile_mobile_money_accounts",
    "finance.approve_reconciliations",
    "finance.record_cash_counts",
    "finance.approve_cash_variances",
    "finance.view_treasury_reports",
    "finance.export_treasury_data",
    "sales.view",
    "sales.create",
    "sales.edit_draft",
    "sales.issue_invoices",
    "sales.receive_payments",
    "sales.view_customer_balances",
    "purchases.view",
    "purchases.create",
    "purchases.approve",
    "purchases.receive_stock",
    "purchases.view_suppliers",
    "purchases.create_suppliers",
    "purchases.edit_suppliers",
    "purchases.view_supplier_prices",
    "purchases.manage_supplier_prices",
    "purchases.create_requisitions",
    "purchases.approve_requisitions",
    "purchases.create_purchase_orders",
    "purchases.edit_draft_purchase_orders",
    "purchases.send_purchase_orders",
    "purchases.inspect_goods",
    "purchases.post_grns",
    "purchases.record_supplier_invoices",
    "purchases.view_supplier_balances",
    "purchases.view_creditor_ageing",
    "purchases.export_purchase_data",
    "inventory.view_stock",
    "inventory.add_products",
    "inventory.edit_products",
    "inventory.adjust_stock",
    "inventory.perform_stock_counts",
    "inventory.view_buying_prices",
    "inventory.view_selling_prices",
    "inventory.transfer_stock",
    "inventory.view_inventory_value",
    "inventory.enter_opening_stock",
    "inventory.receive_transfers",
    "inventory.approve_adjustments",
    "inventory.approve_stock_counts",
    "inventory.view_batches",
    "inventory.export_inventory",
    "distribution.view_deliveries",
    "distribution.create_deliveries",
    "distribution.edit_draft_delivery_runs",
    "distribution.approve_delivery_runs",
    "distribution.assign_vehicles",
    "distribution.assign_drivers",
    "distribution.create_loading_sheets",
    "distribution.pick_stock",
    "distribution.verify_loading",
    "distribution.dispatch_vehicles",
    "distribution.confirm_deliveries",
    "distribution.record_partial_delivery",
    "distribution.record_failed_delivery",
    "distribution.capture_proof_of_delivery",
    "distribution.record_collections",
    "distribution.record_returns",
    "distribution.record_crate_movements",
    "distribution.record_route_expenses",
    "distribution.reconcile_vehicle_stock",
    "distribution.approve_stock_variances",
    "distribution.reconcile_route_collections",
    "distribution.approve_cash_variances",
    "distribution.close_delivery_runs",
    "distribution.view_routes",
    "distribution.view_distribution_reports",
    "distribution.export_distribution_data",
  ],
  staff: ["dashboard.view_staff"],
};

export const staffTemplates: Record<StaffTemplateKey, PermissionKey[]> = {
  salesperson: [
    "dashboard.view_staff",
    "sales.view",
    "sales.create",
    "sales.issue_invoices",
    "sales.view_customer_balances",
  ],
  cashier: [
    "dashboard.view_staff",
    "sales.create",
    "sales.issue_invoices",
    "sales.receive_payments",
    "finance.view_cashbook",
    "finance.create_receipts",
    "finance.record_cash_counts",
  ],
  storekeeper: [
    "dashboard.view_staff",
    "inventory.view_stock",
    "inventory.adjust_stock",
    "inventory.perform_stock_counts",
    "inventory.enter_opening_stock",
    "purchases.receive_stock",
    "purchases.view_suppliers",
    "purchases.inspect_goods",
    "inventory.view_batches",
  ],
  driver: [
    "dashboard.view_staff",
    "distribution.view_assigned_runs",
    "distribution.view_deliveries",
    "distribution.pick_stock",
    "distribution.confirm_arrival",
    "distribution.confirm_deliveries",
    "distribution.record_partial_delivery",
    "distribution.record_failed_delivery",
    "distribution.capture_proof_of_delivery",
    "distribution.record_collections",
    "distribution.record_returns",
    "distribution.record_crate_movements",
    "distribution.record_route_expenses",
  ],
  accountant: [
    "dashboard.view_staff",
    "finance.view_cashbook",
    "finance.view_financial_accounts",
    "finance.view_account_balances",
    "finance.create_receipts",
    "finance.create_payments",
    "finance.approve_payments",
    "finance.record_expenses",
    "finance.approve_expenses",
    "finance.approve_expense_claims",
    "finance.manage_petty_cash",
    "finance.reconcile_petty_cash",
    "finance.create_bank_deposits",
    "finance.verify_bank_deposits",
    "finance.create_withdrawals",
    "finance.create_transfers",
    "finance.confirm_transfers",
    "finance.manage_cheques",
    "finance.view_profit",
    "finance.view_cash_flow",
    "finance.export_financial_reports",
    "finance.issue_staff_advances",
    "finance.review_advance_surrender",
    "finance.view_driver_cash",
    "finance.import_statements",
    "finance.reconcile_bank_accounts",
    "finance.reconcile_mobile_money_accounts",
    "finance.record_cash_counts",
    "finance.view_treasury_reports",
    "finance.export_treasury_data",
    "purchases.record_supplier_invoices",
    "purchases.record_supplier_payments",
    "purchases.view_supplier_balances",
    "purchases.view_creditor_ageing",
    "sales.view_customer_balances",
  ],
  custom: ["dashboard.view_staff"],
};

export function permissionsForRole(role: CoreRole, overrides: PermissionKey[] = []) {
  return Array.from(new Set([...roleDefaults[role], ...overrides]));
}

export function canPerformAction(membership: Membership | null, permission: PermissionKey) {
  if (!membership?.active) return false;
  if (membership.role === "owner") return true;
  return permissionsForRole(membership.role, membership.permissions).includes(permission);
}

export function requirePermission(membership: Membership | null, permission: PermissionKey) {
  if (!canPerformAction(membership, permission)) {
    throw new Error("You do not have permission to perform this action.");
  }
  return true;
}

export function requireRole(membership: Membership | null, roles: CoreRole[]) {
  if (!membership?.active || !roles.includes(membership.role)) {
    throw new Error("This role cannot perform the requested action.");
  }
  return true;
}

export function assertOwnerProtection({
  acting,
  target,
  activeOwnerCount,
  nextRole,
  deactivate,
}: {
  acting: Membership;
  target: Membership;
  activeOwnerCount: number;
  nextRole?: CoreRole;
  deactivate?: boolean;
}) {
  requirePermission(acting, "administration.manage_users");
  if (target.role === "owner" && (deactivate || nextRole !== "owner") && activeOwnerCount <= 1) {
    throw new Error("A business must retain at least one active Owner.");
  }
}
