import type {
  CoreRole,
  Membership,
  PermissionCategory,
  PermissionKey,
  StaffTemplateKey,
} from "./types";

export const permissionCatalog: Record<
  PermissionCategory,
  { label: string; permissions: { key: PermissionKey; label: string }[] }
> = {
  dashboard: {
    label: "Dashboard",
    permissions: [
      { key: "dashboard.view_owner", label: "View owner dashboard" },
      { key: "dashboard.view_manager", label: "View manager dashboard" },
      { key: "dashboard.view_staff", label: "View staff dashboard" },
      { key: "dashboard.view_command_centre", label: "View command centre" },
      { key: "dashboard.view_role_dashboards", label: "View role dashboards" },
      { key: "dashboard.view_business_health", label: "View business health" },
      { key: "dashboard.view_business_insights", label: "View business insights" },
      {
        key: "dashboard.view_sensitive_financial_summaries",
        label: "View sensitive financial summaries",
      },
      { key: "dashboard.manage_layouts", label: "Manage dashboard layouts" },
      { key: "dashboard.manage_kpis", label: "Manage KPI definitions" },
      { key: "dashboard.manage_alerts", label: "Manage business alerts" },
      { key: "dashboard.manage_recommendations", label: "Manage recommendations" },
      { key: "dashboard.view_data_quality", label: "View data quality" },
      { key: "dashboard.view_system_health", label: "View system health" },
      { key: "dashboard.schedule_reports", label: "Schedule reports" },
      { key: "dashboard.view_business_memory", label: "View business memory" },
      { key: "dashboard.export_executive_pack", label: "Export executive pack" },
    ],
  },
  sales: {
    label: "Sales",
    permissions: [
      { key: "sales.view", label: "View sales" },
      { key: "sales.create", label: "Create sales" },
      { key: "sales.edit_draft", label: "Edit draft sales" },
      { key: "sales.approve_discounts", label: "Approve discounts" },
      { key: "sales.issue_invoices", label: "Issue invoices" },
      { key: "sales.receive_payments", label: "Receive payments" },
      { key: "sales.cancel_invoices", label: "Cancel invoices" },
      { key: "sales.view_customer_balances", label: "View customer balances" },
    ],
  },
  purchases: {
    label: "Purchases",
    permissions: [
      { key: "purchases.view", label: "View purchases" },
      { key: "purchases.create", label: "Create purchases" },
      { key: "purchases.approve", label: "Approve purchases" },
      { key: "purchases.receive_stock", label: "Receive stock" },
      { key: "purchases.record_supplier_invoices", label: "Record supplier invoices" },
      { key: "purchases.record_supplier_payments", label: "Record supplier payments" },
      { key: "purchases.view_suppliers", label: "View suppliers" },
      { key: "purchases.create_suppliers", label: "Create suppliers" },
      { key: "purchases.edit_suppliers", label: "Edit suppliers" },
      { key: "purchases.approve_suppliers", label: "Approve suppliers" },
      { key: "purchases.view_supplier_prices", label: "View supplier prices" },
      { key: "purchases.manage_supplier_prices", label: "Manage supplier prices" },
      { key: "purchases.view_supplier_documents", label: "View supplier documents" },
      { key: "purchases.create_requisitions", label: "Create requisitions" },
      { key: "purchases.approve_requisitions", label: "Approve requisitions" },
      { key: "purchases.create_purchase_orders", label: "Create purchase orders" },
      { key: "purchases.edit_draft_purchase_orders", label: "Edit draft purchase orders" },
      { key: "purchases.approve_purchase_orders", label: "Approve purchase orders" },
      { key: "purchases.send_purchase_orders", label: "Send purchase orders" },
      { key: "purchases.inspect_goods", label: "Inspect goods" },
      { key: "purchases.approve_grns", label: "Approve GRNs" },
      { key: "purchases.post_grns", label: "Post GRNs" },
      { key: "purchases.approve_supplier_bills", label: "Approve supplier bills" },
      { key: "purchases.override_match_exceptions", label: "Override match exceptions" },
      { key: "purchases.create_supplier_returns", label: "Create supplier returns" },
      { key: "purchases.approve_supplier_returns", label: "Approve supplier returns" },
      { key: "purchases.approve_supplier_payments", label: "Approve supplier payments" },
      { key: "purchases.view_supplier_balances", label: "View supplier balances" },
      { key: "purchases.view_creditor_ageing", label: "View creditor ageing" },
      { key: "purchases.export_purchase_data", label: "Export purchase data" },
      { key: "purchases.import_supplier_data", label: "Import supplier data" },
      { key: "purchases.reverse_purchase_transactions", label: "Reverse purchase transactions" },
    ],
  },
  inventory: {
    label: "Inventory",
    permissions: [
      { key: "inventory.view_stock", label: "View stock" },
      { key: "inventory.add_products", label: "Add products" },
      { key: "inventory.edit_products", label: "Edit products" },
      { key: "inventory.adjust_stock", label: "Adjust stock" },
      { key: "inventory.perform_stock_counts", label: "Perform stock counts" },
      { key: "inventory.view_buying_prices", label: "View buying prices" },
      { key: "inventory.view_selling_prices", label: "View selling prices" },
      { key: "inventory.transfer_stock", label: "Transfer stock" },
      { key: "inventory.archive_products", label: "Archive products" },
      { key: "inventory.view_inventory_value", label: "View inventory value" },
      { key: "inventory.enter_opening_stock", label: "Enter opening stock" },
      { key: "inventory.receive_transfers", label: "Receive transfers" },
      { key: "inventory.approve_adjustments", label: "Approve stock adjustments" },
      { key: "inventory.approve_stock_counts", label: "Approve stock counts" },
      { key: "inventory.view_batches", label: "View batches" },
      { key: "inventory.dispose_expired_stock", label: "Dispose expired stock" },
      { key: "inventory.manage_serial_numbers", label: "Manage serial numbers" },
      { key: "inventory.export_inventory", label: "Export inventory" },
      { key: "inventory.revalue_stock", label: "Revalue stock" },
      { key: "inventory.close_inventory_periods", label: "Close inventory periods" },
    ],
  },
  finance: {
    label: "Finance",
    permissions: [
      { key: "finance.view_cashbook", label: "View cashbook" },
      { key: "finance.view_financial_accounts", label: "View financial accounts" },
      { key: "finance.create_financial_accounts", label: "Create financial accounts" },
      { key: "finance.edit_financial_accounts", label: "Edit financial accounts" },
      { key: "finance.view_full_account_details", label: "View full account details" },
      { key: "finance.view_account_balances", label: "View account balances" },
      { key: "finance.create_receipts", label: "Create receipts" },
      { key: "finance.create_payments", label: "Create payments" },
      { key: "finance.approve_payments", label: "Approve payments" },
      { key: "finance.record_expenses", label: "Record expenses" },
      { key: "finance.approve_expenses", label: "Approve expenses" },
      { key: "finance.submit_expense_claims", label: "Submit expense claims" },
      { key: "finance.approve_expense_claims", label: "Approve expense claims" },
      { key: "finance.manage_petty_cash", label: "Manage petty cash" },
      { key: "finance.reconcile_petty_cash", label: "Reconcile petty cash" },
      { key: "finance.create_bank_deposits", label: "Create bank deposits" },
      { key: "finance.verify_bank_deposits", label: "Verify bank deposits" },
      { key: "finance.create_withdrawals", label: "Create withdrawals" },
      { key: "finance.create_transfers", label: "Create transfers" },
      { key: "finance.approve_transfers", label: "Approve transfers" },
      { key: "finance.confirm_transfers", label: "Confirm transfers" },
      { key: "finance.manage_cheques", label: "Manage cheques" },
      { key: "finance.view_profit", label: "View profit" },
      { key: "finance.view_balance_sheet", label: "View balance sheet" },
      { key: "finance.view_cash_flow", label: "View cash flow" },
      { key: "finance.view_owner_transactions", label: "View owner transactions" },
      { key: "finance.record_owner_transactions", label: "Record owner transactions" },
      { key: "finance.approve_owner_transactions", label: "Approve owner transactions" },
      { key: "finance.issue_staff_advances", label: "Issue staff advances" },
      { key: "finance.approve_staff_advances", label: "Approve staff advances" },
      { key: "finance.review_advance_surrender", label: "Review advance surrender" },
      { key: "finance.view_driver_cash", label: "View driver cash" },
      { key: "finance.record_cash_handover", label: "Record cash handover" },
      { key: "finance.import_statements", label: "Import statements" },
      { key: "finance.reconcile_bank_accounts", label: "Reconcile bank accounts" },
      { key: "finance.reconcile_mobile_money_accounts", label: "Reconcile mobile-money accounts" },
      { key: "finance.approve_reconciliations", label: "Approve reconciliations" },
      { key: "finance.reopen_reconciliations", label: "Reopen reconciliations" },
      { key: "finance.record_cash_counts", label: "Record cash counts" },
      { key: "finance.approve_cash_variances", label: "Approve cash variances" },
      { key: "finance.view_treasury_reports", label: "View treasury reports" },
      { key: "finance.export_treasury_data", label: "Export treasury data" },
      { key: "finance.reverse_treasury_transactions", label: "Reverse treasury transactions" },
      { key: "finance.close_accounting_periods", label: "Close accounting periods" },
      { key: "finance.export_financial_reports", label: "Export financial reports" },
    ],
  },
  accounting: {
    label: "Accounting",
    permissions: [
      { key: "accounting.view_chart_of_accounts", label: "View chart of accounts" },
      { key: "accounting.create_accounts", label: "Create accounts" },
      { key: "accounting.edit_accounts", label: "Edit accounts" },
      { key: "accounting.archive_accounts", label: "Archive accounts" },
      { key: "accounting.manage_account_roles", label: "Manage account roles" },
      { key: "accounting.manage_account_mappings", label: "Manage account mappings" },
      { key: "accounting.import_chart_of_accounts", label: "Import chart of accounts" },
      { key: "accounting.view_accounting_events", label: "View accounting events" },
      { key: "accounting.retry_failed_events", label: "Retry failed events" },
      { key: "accounting.create_manual_journals", label: "Create manual journals" },
      { key: "accounting.edit_draft_journals", label: "Edit draft journals" },
      { key: "accounting.submit_journals", label: "Submit journals" },
      { key: "accounting.approve_journals", label: "Approve journals" },
      { key: "accounting.post_journals", label: "Post journals" },
      { key: "accounting.reverse_journals", label: "Reverse journals" },
      { key: "accounting.import_journals", label: "Import journals" },
      { key: "accounting.view_general_ledger", label: "View general ledger" },
      { key: "accounting.view_trial_balance", label: "View trial balance" },
      { key: "accounting.view_control_accounts", label: "View control accounts" },
      { key: "accounting.reconcile_subledgers", label: "Reconcile subledgers" },
      { key: "accounting.view_tax_ledgers", label: "View tax ledgers" },
      { key: "accounting.manage_financial_years", label: "Manage financial years" },
      { key: "accounting.manage_accounting_periods", label: "Manage accounting periods" },
      { key: "accounting.soft_close_periods", label: "Soft close periods" },
      { key: "accounting.close_periods", label: "Close periods" },
      { key: "accounting.reopen_periods", label: "Reopen periods" },
      { key: "accounting.post_to_control_accounts", label: "Post to control accounts" },
      { key: "accounting.post_to_inventory_accounts", label: "Post to inventory accounts" },
      { key: "accounting.post_backdated_journals", label: "Post backdated journals" },
      { key: "accounting.view_accounting_reports", label: "View accounting reports" },
      { key: "accounting.export_accounting_data", label: "Export accounting data" },
      { key: "accounting.view_accounting_audit_trail", label: "View accounting audit trail" },
    ],
  },
  financial_reporting: {
    label: "Financial Reporting",
    permissions: [
      { key: "financial_reporting.view_statements", label: "View financial statements" },
      { key: "financial_reporting.view_branch_statements", label: "View branch statements" },
      { key: "financial_reporting.view_consolidated_statements", label: "View consolidated statements" },
      { key: "financial_reporting.configure_statement_layouts", label: "Configure statement layouts" },
      { key: "financial_reporting.generate_management_accounts", label: "Generate management accounts" },
      { key: "financial_reporting.add_management_commentary", label: "Add management commentary" },
      { key: "financial_reporting.approve_financial_statements", label: "Approve financial statements" },
      { key: "financial_reporting.create_budgets", label: "Create budgets" },
      { key: "financial_reporting.edit_draft_budgets", label: "Edit draft budgets" },
      { key: "financial_reporting.submit_budgets", label: "Submit budgets" },
      { key: "financial_reporting.approve_budgets", label: "Approve budgets" },
      { key: "financial_reporting.activate_budgets", label: "Activate budgets" },
      { key: "financial_reporting.create_forecasts", label: "Create forecasts" },
      { key: "financial_reporting.approve_forecasts", label: "Approve forecasts" },
      { key: "financial_reporting.view_financial_ratios", label: "View financial ratios" },
      { key: "financial_reporting.view_profitability_reports", label: "View profitability reports" },
      { key: "financial_reporting.view_owner_financial_information", label: "View owner financial information" },
      { key: "financial_reporting.start_period_close", label: "Start period close" },
      { key: "financial_reporting.complete_close_tasks", label: "Complete close tasks" },
      { key: "financial_reporting.waive_close_tasks", label: "Waive close tasks" },
      { key: "financial_reporting.create_adjustment_journals", label: "Create adjustment journals" },
      { key: "financial_reporting.approve_adjustment_journals", label: "Approve adjustment journals" },
      { key: "financial_reporting.soft_close_periods", label: "Soft close periods" },
      { key: "financial_reporting.hard_close_periods", label: "Hard close periods" },
      { key: "financial_reporting.request_period_reopening", label: "Request period reopening" },
      { key: "financial_reporting.approve_period_reopening", label: "Approve period reopening" },
      { key: "financial_reporting.close_financial_years", label: "Close financial years" },
      { key: "financial_reporting.run_year_end_transfer", label: "Run year-end transfer" },
      { key: "financial_reporting.view_period_close_audit_trail", label: "View period-close audit trail" },
      { key: "financial_reporting.export_financial_reports", label: "Export financial reports" },
      { key: "financial_reporting.view_statement_snapshots", label: "View statement snapshots" },
    ],
  },
  tax_compliance: {
    label: "Tax Compliance",
    permissions: [
      { key: "tax.view_business_tax_profile", label: "View business tax profile" },
      { key: "tax.edit_business_tax_profile", label: "Edit business tax profile" },
      { key: "tax.manage_tax_rules", label: "Manage tax rules" },
      { key: "tax.manage_vat_codes", label: "Manage VAT codes" },
      { key: "tax.manage_tax_mappings", label: "Manage product tax mappings" },
      { key: "tax.edit_customer_tax_profile", label: "Edit customer tax profiles" },
      { key: "tax.edit_supplier_tax_profile", label: "Edit supplier tax profiles" },
      { key: "tax.override_tax_code", label: "Override tax codes" },
      { key: "tax.override_tax_date", label: "Override tax dates" },
      { key: "tax.view_tax_calculations", label: "View tax calculations" },
      { key: "tax.submit_etims_documents", label: "Submit eTIMS documents" },
      { key: "tax.retry_etims_submissions", label: "Retry eTIMS submissions" },
      { key: "tax.record_manual_external_references", label: "Record manual external references" },
      { key: "tax.approve_credit_notes", label: "Approve credit notes" },
      { key: "tax.approve_debit_notes", label: "Approve debit notes" },
      { key: "tax.verify_purchase_tax_documents", label: "Verify purchase tax documents" },
      { key: "tax.review_input_vat_eligibility", label: "Review input VAT eligibility" },
      { key: "tax.prepare_vat_returns", label: "Prepare VAT returns" },
      { key: "tax.approve_vat_returns", label: "Approve VAT returns" },
      { key: "tax.record_filing_references", label: "Record filing references" },
      { key: "tax.record_tax_payments", label: "Record tax payments" },
      { key: "tax.prepare_withholding_returns", label: "Prepare withholding returns" },
      { key: "tax.manage_withholding_certificates", label: "Manage withholding certificates" },
      { key: "tax.manage_tax_calendar", label: "Manage tax calendar" },
      { key: "tax.close_tax_periods", label: "Close tax periods" },
      { key: "tax.reopen_tax_periods", label: "Reopen tax periods" },
      { key: "tax.view_tax_reports", label: "View tax reports" },
      { key: "tax.export_tax_data", label: "Export tax data" },
      { key: "tax.view_integration_health", label: "View integration health" },
      { key: "tax.configure_tax_integration", label: "Configure tax integration" },
      { key: "tax.view_tax_audit_evidence", label: "View tax audit evidence" },
      { key: "tax.view_tax_audit_trail", label: "View tax audit trail" },
    ],
  },
  distribution: {
    label: "Distribution",
    permissions: [
      { key: "distribution.view_deliveries", label: "View deliveries" },
      { key: "distribution.create_deliveries", label: "Create deliveries" },
      { key: "distribution.edit_draft_delivery_runs", label: "Edit draft delivery runs" },
      { key: "distribution.approve_delivery_runs", label: "Approve delivery runs" },
      { key: "distribution.assign_vehicles", label: "Assign vehicles" },
      { key: "distribution.assign_drivers", label: "Assign drivers" },
      { key: "distribution.create_loading_sheets", label: "Create loading sheets" },
      { key: "distribution.pick_stock", label: "Pick stock" },
      { key: "distribution.verify_loading", label: "Verify loading" },
      { key: "distribution.dispatch_vehicles", label: "Dispatch vehicles" },
      { key: "distribution.view_assigned_runs", label: "View assigned runs" },
      { key: "distribution.confirm_arrival", label: "Confirm arrival" },
      { key: "distribution.confirm_deliveries", label: "Confirm deliveries" },
      { key: "distribution.record_partial_delivery", label: "Record partial delivery" },
      { key: "distribution.record_failed_delivery", label: "Record failed delivery" },
      { key: "distribution.capture_proof_of_delivery", label: "Capture proof of delivery" },
      { key: "distribution.record_collections", label: "Record collections" },
      { key: "distribution.record_returns", label: "Record returns" },
      { key: "distribution.record_crate_movements", label: "Record crate movements" },
      { key: "distribution.record_route_expenses", label: "Record route expenses" },
      { key: "distribution.reconcile_vehicle_stock", label: "Reconcile vehicle stock" },
      { key: "distribution.approve_stock_variances", label: "Approve stock variances" },
      { key: "distribution.reconcile_route_collections", label: "Reconcile route collections" },
      { key: "distribution.approve_cash_variances", label: "Approve cash variances" },
      { key: "distribution.close_delivery_runs", label: "Close delivery runs" },
      { key: "distribution.reopen_delivery_runs", label: "Reopen delivery runs" },
      { key: "distribution.view_routes", label: "View routes" },
      { key: "distribution.view_distribution_reports", label: "View distribution reports" },
      { key: "distribution.export_distribution_data", label: "Export distribution data" },
    ],
  },
  administration: {
    label: "Administration",
    permissions: [
      { key: "administration.manage_users", label: "Manage users" },
      { key: "administration.manage_permissions", label: "Manage permissions" },
      { key: "administration.manage_business_settings", label: "Manage business settings" },
      { key: "administration.view_audit_logs", label: "View audit logs" },
      { key: "administration.export_data", label: "Export data" },
      { key: "administration.delete_draft_records", label: "Delete draft records" },
      { key: "administration.approve_sensitive_actions", label: "Approve sensitive actions" },
    ],
  },
};

export const allPermissions = Object.values(permissionCatalog).flatMap((category) =>
  category.permissions.map((permission) => permission.key),
);

export const roleDefaults: Record<CoreRole, PermissionKey[]> = {
  owner: allPermissions,
  manager: [
    "dashboard.view_manager",
    "dashboard.view_command_centre",
    "dashboard.view_role_dashboards",
    "dashboard.view_business_health",
    "dashboard.view_business_insights",
    "dashboard.manage_layouts",
    "dashboard.manage_alerts",
    "dashboard.manage_recommendations",
    "dashboard.view_data_quality",
    "dashboard.schedule_reports",
    "dashboard.view_business_memory",
    "dashboard.export_executive_pack",
    "finance.view_cashbook",
    "finance.view_financial_accounts",
    "finance.view_account_balances",
    "finance.create_receipts",
    "finance.create_payments",
    "finance.approve_payments",
    "finance.record_expenses",
    "finance.approve_expenses",
    "finance.approve_expense_claims",
    "finance.manage_petty_cash",
    "finance.reconcile_petty_cash",
    "finance.create_bank_deposits",
    "finance.verify_bank_deposits",
    "finance.create_withdrawals",
    "finance.create_transfers",
    "finance.approve_transfers",
    "finance.confirm_transfers",
    "finance.manage_cheques",
    "finance.view_cash_flow",
    "finance.issue_staff_advances",
    "finance.approve_staff_advances",
    "finance.review_advance_surrender",
    "finance.view_driver_cash",
    "finance.record_cash_handover",
    "finance.import_statements",
    "finance.reconcile_bank_accounts",
    "finance.reconcile_mobile_money_accounts",
    "finance.approve_reconciliations",
    "finance.record_cash_counts",
    "finance.approve_cash_variances",
    "finance.view_treasury_reports",
    "finance.export_treasury_data",
    "accounting.view_chart_of_accounts",
    "accounting.view_accounting_events",
    "accounting.create_manual_journals",
    "accounting.submit_journals",
    "accounting.approve_journals",
    "accounting.post_journals",
    "accounting.view_general_ledger",
    "accounting.view_trial_balance",
    "accounting.view_control_accounts",
    "accounting.reconcile_subledgers",
    "accounting.view_tax_ledgers",
    "accounting.view_accounting_reports",
    "accounting.export_accounting_data",
    "financial_reporting.view_statements",
    "financial_reporting.view_branch_statements",
    "financial_reporting.view_consolidated_statements",
    "financial_reporting.generate_management_accounts",
    "financial_reporting.add_management_commentary",
    "financial_reporting.create_budgets",
    "financial_reporting.edit_draft_budgets",
    "financial_reporting.submit_budgets",
    "financial_reporting.create_forecasts",
    "financial_reporting.view_financial_ratios",
    "financial_reporting.view_profitability_reports",
    "financial_reporting.start_period_close",
    "financial_reporting.complete_close_tasks",
    "financial_reporting.create_adjustment_journals",
    "financial_reporting.soft_close_periods",
    "financial_reporting.export_financial_reports",
    "financial_reporting.view_statement_snapshots",
    "tax.view_business_tax_profile",
    "tax.manage_tax_mappings",
    "tax.view_tax_calculations",
    "tax.submit_etims_documents",
    "tax.retry_etims_submissions",
    "tax.record_manual_external_references",
    "tax.approve_credit_notes",
    "tax.approve_debit_notes",
    "tax.verify_purchase_tax_documents",
    "tax.review_input_vat_eligibility",
    "tax.prepare_vat_returns",
    "tax.record_filing_references",
    "tax.record_tax_payments",
    "tax.prepare_withholding_returns",
    "tax.manage_withholding_certificates",
    "tax.manage_tax_calendar",
    "tax.close_tax_periods",
    "tax.view_tax_reports",
    "tax.export_tax_data",
    "tax.view_integration_health",
    "tax.view_tax_audit_evidence",
    "sales.view",
    "sales.create",
    "sales.edit_draft",
    "sales.issue_invoices",
    "sales.receive_payments",
    "sales.view_customer_balances",
    "purchases.view",
    "purchases.create",
    "purchases.approve",
    "purchases.receive_stock",
    "purchases.view_suppliers",
    "purchases.create_suppliers",
    "purchases.edit_suppliers",
    "purchases.view_supplier_prices",
    "purchases.manage_supplier_prices",
    "purchases.create_requisitions",
    "purchases.approve_requisitions",
    "purchases.create_purchase_orders",
    "purchases.edit_draft_purchase_orders",
    "purchases.send_purchase_orders",
    "purchases.inspect_goods",
    "purchases.post_grns",
    "purchases.record_supplier_invoices",
    "purchases.view_supplier_balances",
    "purchases.view_creditor_ageing",
    "purchases.export_purchase_data",
    "inventory.view_stock",
    "inventory.add_products",
    "inventory.edit_products",
    "inventory.adjust_stock",
    "inventory.perform_stock_counts",
    "inventory.view_buying_prices",
    "inventory.view_selling_prices",
    "inventory.transfer_stock",
    "inventory.view_inventory_value",
    "inventory.enter_opening_stock",
    "inventory.receive_transfers",
    "inventory.approve_adjustments",
    "inventory.approve_stock_counts",
    "inventory.view_batches",
    "inventory.export_inventory",
    "distribution.view_deliveries",
    "distribution.create_deliveries",
    "distribution.edit_draft_delivery_runs",
    "distribution.approve_delivery_runs",
    "distribution.assign_vehicles",
    "distribution.assign_drivers",
    "distribution.create_loading_sheets",
    "distribution.pick_stock",
    "distribution.verify_loading",
    "distribution.dispatch_vehicles",
    "distribution.confirm_deliveries",
    "distribution.record_partial_delivery",
    "distribution.record_failed_delivery",
    "distribution.capture_proof_of_delivery",
    "distribution.record_collections",
    "distribution.record_returns",
    "distribution.record_crate_movements",
    "distribution.record_route_expenses",
    "distribution.reconcile_vehicle_stock",
    "distribution.approve_stock_variances",
    "distribution.reconcile_route_collections",
    "distribution.approve_cash_variances",
    "distribution.close_delivery_runs",
    "distribution.view_routes",
    "distribution.view_distribution_reports",
    "distribution.export_distribution_data",
  ],
  staff: ["dashboard.view_staff"],
};

export const staffTemplates: Record<StaffTemplateKey, PermissionKey[]> = {
  salesperson: [
    "dashboard.view_staff",
    "dashboard.view_role_dashboards",
    "sales.view",
    "sales.create",
    "sales.issue_invoices",
    "sales.view_customer_balances",
  ],
  cashier: [
    "dashboard.view_staff",
    "dashboard.view_role_dashboards",
    "sales.create",
    "sales.issue_invoices",
    "sales.receive_payments",
    "finance.view_cashbook",
    "finance.create_receipts",
    "finance.record_cash_counts",
  ],
  storekeeper: [
    "dashboard.view_staff",
    "dashboard.view_role_dashboards",
    "inventory.view_stock",
    "inventory.adjust_stock",
    "inventory.perform_stock_counts",
    "inventory.enter_opening_stock",
    "purchases.receive_stock",
    "purchases.view_suppliers",
    "purchases.inspect_goods",
    "inventory.view_batches",
  ],
  driver: [
    "dashboard.view_staff",
    "dashboard.view_role_dashboards",
    "distribution.view_assigned_runs",
    "distribution.view_deliveries",
    "distribution.pick_stock",
    "distribution.confirm_arrival",
    "distribution.confirm_deliveries",
    "distribution.record_partial_delivery",
    "distribution.record_failed_delivery",
    "distribution.capture_proof_of_delivery",
    "distribution.record_collections",
    "distribution.record_returns",
    "distribution.record_crate_movements",
    "distribution.record_route_expenses",
  ],
  accountant: [
    "dashboard.view_staff",
    "dashboard.view_role_dashboards",
    "dashboard.view_business_health",
    "dashboard.view_business_insights",
    "dashboard.manage_layouts",
    "dashboard.view_data_quality",
    "dashboard.schedule_reports",
    "finance.view_cashbook",
    "finance.view_financial_accounts",
    "finance.view_account_balances",
    "finance.create_receipts",
    "finance.create_payments",
    "finance.approve_payments",
    "finance.record_expenses",
    "finance.approve_expenses",
    "finance.approve_expense_claims",
    "finance.manage_petty_cash",
    "finance.reconcile_petty_cash",
    "finance.create_bank_deposits",
    "finance.verify_bank_deposits",
    "finance.create_withdrawals",
    "finance.create_transfers",
    "finance.confirm_transfers",
    "finance.manage_cheques",
    "finance.view_profit",
    "finance.view_cash_flow",
    "finance.export_financial_reports",
    "accounting.view_chart_of_accounts",
    "accounting.manage_account_mappings",
    "accounting.view_accounting_events",
    "accounting.retry_failed_events",
    "accounting.create_manual_journals",
    "accounting.edit_draft_journals",
    "accounting.submit_journals",
    "accounting.view_general_ledger",
    "accounting.view_trial_balance",
    "accounting.view_control_accounts",
    "accounting.reconcile_subledgers",
    "accounting.view_tax_ledgers",
    "accounting.view_accounting_reports",
    "accounting.export_accounting_data",
    "financial_reporting.view_statements",
    "financial_reporting.view_branch_statements",
    "financial_reporting.generate_management_accounts",
    "financial_reporting.add_management_commentary",
    "financial_reporting.create_budgets",
    "financial_reporting.edit_draft_budgets",
    "financial_reporting.submit_budgets",
    "financial_reporting.create_forecasts",
    "financial_reporting.view_financial_ratios",
    "financial_reporting.view_profitability_reports",
    "financial_reporting.complete_close_tasks",
    "financial_reporting.create_adjustment_journals",
    "financial_reporting.export_financial_reports",
    "tax.view_business_tax_profile",
    "tax.manage_vat_codes",
    "tax.manage_tax_mappings",
    "tax.view_tax_calculations",
    "tax.submit_etims_documents",
    "tax.retry_etims_submissions",
    "tax.record_manual_external_references",
    "tax.verify_purchase_tax_documents",
    "tax.review_input_vat_eligibility",
    "tax.prepare_vat_returns",
    "tax.record_filing_references",
    "tax.record_tax_payments",
    "tax.prepare_withholding_returns",
    "tax.manage_withholding_certificates",
    "tax.view_tax_reports",
    "tax.export_tax_data",
    "tax.view_integration_health",
    "tax.view_tax_audit_evidence",
    "tax.view_tax_audit_trail",
    "finance.issue_staff_advances",
    "finance.review_advance_surrender",
    "finance.view_driver_cash",
    "finance.import_statements",
    "finance.reconcile_bank_accounts",
    "finance.reconcile_mobile_money_accounts",
    "finance.record_cash_counts",
    "finance.view_treasury_reports",
    "finance.export_treasury_data",
    "purchases.record_supplier_invoices",
    "purchases.record_supplier_payments",
    "purchases.view_supplier_balances",
    "purchases.view_creditor_ageing",
    "sales.view_customer_balances",
  ],
  custom: ["dashboard.view_staff"],
};

export function permissionsForRole(role: CoreRole, overrides: PermissionKey[] = []) {
  return Array.from(new Set([...roleDefaults[role], ...overrides]));
}

export function canPerformAction(membership: Membership | null, permission: PermissionKey) {
  if (!membership?.active) return false;
  if (membership.role === "owner") return true;
  return permissionsForRole(membership.role, membership.permissions).includes(permission);
}

export function requirePermission(membership: Membership | null, permission: PermissionKey) {
  if (!canPerformAction(membership, permission)) {
    throw new Error("You do not have permission to perform this action.");
  }
  return true;
}

export function requireRole(membership: Membership | null, roles: CoreRole[]) {
  if (!membership?.active || !roles.includes(membership.role)) {
    throw new Error("This role cannot perform the requested action.");
  }
  return true;
}

export function assertOwnerProtection({
  acting,
  target,
  activeOwnerCount,
  nextRole,
  deactivate,
}: {
  acting: Membership;
  target: Membership;
  activeOwnerCount: number;
  nextRole?: CoreRole;
  deactivate?: boolean;
}) {
  requirePermission(acting, "administration.manage_users");
  if (target.role === "owner" && (deactivate || nextRole !== "owner") && activeOwnerCount <= 1) {
    throw new Error("A business must retain at least one active Owner.");
  }
}
