import { classifyLaunchReadiness, launchReadinessAreas, type Plan } from "./saas-platform";

export const commercialPlans: Plan[] = [
  {
    code: "starter",
    name: "Starter",
    currency: "KES",
    interval: "monthly",
    basePrice: 2500,
    trialDays: 14,
    limits: { users: 3, branches: 1, warehouses: 1, products: 500, monthlyInvoices: 300, storageMb: 1024 },
    entitlements: { inventory: true, purchasing: true, sales: true, exports: true, command_centre: true },
  },
  {
    code: "growth",
    name: "Growth",
    currency: "KES",
    interval: "monthly",
    basePrice: 6500,
    trialDays: 14,
    limits: { users: 10, branches: 3, warehouses: 5, products: 5000, monthlyInvoices: 2000, storageMb: 5120 },
    entitlements: { inventory: true, purchasing: true, sales: true, distribution: true, accounting: true, tax_management: true, scheduled_reports: true },
  },
  {
    code: "professional",
    name: "Professional",
    currency: "KES",
    interval: "monthly",
    basePrice: 14500,
    trialDays: 14,
    limits: { users: 30, branches: 10, warehouses: 20, products: 25000, monthlyInvoices: 10000, storageMb: 20480 },
    entitlements: { inventory: true, purchasing: true, sales: true, distribution: true, accounting: true, financial_statements: true, budgets: true, tax_management: true, etims_integration: true, advanced_dashboards: true, api_access: true },
  },
  {
    code: "enterprise",
    name: "Enterprise",
    currency: "KES",
    interval: "custom",
    basePrice: 0,
    trialDays: 30,
    limits: { users: null, branches: null, warehouses: null, products: null, monthlyInvoices: null, storageMb: null },
    entitlements: { inventory: true, purchasing: true, sales: true, distribution: true, accounting: true, financial_statements: true, budgets: true, tax_management: true, etims_integration: true, advanced_dashboards: true, api_access: true, premium_support: true },
  },
];

export const lifecycleStatuses = [
  ["Pending Verification", "Workspace awaits business verification before live operations."],
  ["Onboarding", "Setup can continue; live transaction posting stays restricted until go-live."],
  ["Trial", "Access follows trial plan, expiry reminders and usage limits."],
  ["Active", "Full access within subscription limits and permissions."],
  ["Grace Period", "Billing warning state before stricter restrictions."],
  ["Payment Overdue", "Owners see billing alerts and high-risk actions may be restricted."],
  ["Restricted", "Read and critical exports remain; new operational transactions are blocked."],
  ["Suspended", "Read-only access is preserved with billing and data export access."],
  ["Cancelled", "Retention period begins and reactivation policy applies."],
  ["Archived", "Workspace is preserved outside normal operations."],
  ["Scheduled for Deletion", "Advance notice, confirmation and legal-hold checks are required."],
];

export const platformRoles = [
  ["Platform Super Administrator", "Full platform configuration and emergency access."],
  ["Platform Operations Administrator", "Operational health, onboarding and support coordination."],
  ["Platform Support Agent", "Support cases and approved support access only."],
  ["Platform Finance Administrator", "Subscription invoices, payments and manual verification."],
  ["Platform Security Reviewer", "Security events, platform audit and access reviews."],
  ["Read-Only Platform Auditor", "Read-only platform audit access."],
];

export const onboardingStages = [
  "Welcome",
  "Business Profile",
  "Legal and Tax Details",
  "Branches",
  "Warehouses",
  "Users and Roles",
  "Products or Services",
  "Customers",
  "Suppliers",
  "Opening Inventory",
  "Financial Accounts",
  "Accounting Setup",
  "Tax Setup",
  "Document Numbering",
  "Approval Policies",
  "Subscription Selection",
  "Data Import",
  "Review",
  "Go Live",
];

export const industryTemplates = [
  "Distributor",
  "Wholesaler",
  "Retailer",
  "Restaurant",
  "Pharmacy",
  "Hardware Store",
  "Manufacturer",
  "Service Business",
  "General SME",
];

export const importCentreTypes = [
  "Products",
  "Inventory",
  "Customers",
  "Suppliers",
  "Opening balances",
  "Chart of accounts",
  "Bank balances",
  "Customer balances",
  "Supplier balances",
  "Price lists",
  "Packaging balances",
  "Vehicles",
  "Routes",
  "Users",
  "Budgets",
  "Historical transactions",
];

export const goLiveChecks = [
  "Business profile complete",
  "At least one branch",
  "At least one authorised Owner",
  "Subscription active or trial valid",
  "Tax profile reviewed",
  "Chart of accounts ready where accounting enabled",
  "Critical account mappings complete",
  "Financial accounts configured",
  "Document numbering configured",
  "Products or services loaded",
  "Opening balances reviewed",
  "Inventory balances reviewed",
  "Users and permissions reviewed",
  "Approval policies reviewed",
  "eTIMS setup reviewed where applicable",
  "Backups enabled",
  "Data-import errors resolved",
  "Security settings reviewed",
  "Support contact available",
];

export const productionEnvReference = [
  ["NEXT_PUBLIC_APP_URL", "Canonical app URL", "Production, preview", "Public", "https://solva-trade.vercel.app"],
  ["NEXT_PUBLIC_SUPABASE_URL", "Supabase project URL", "All", "Public", "https://project.supabase.co"],
  ["NEXT_PUBLIC_SUPABASE_ANON_KEY", "Supabase publishable or anon key", "All", "Public", "sb_publishable_..."],
  ["SUPABASE_SERVICE_ROLE_KEY", "Server-side privileged maintenance tasks", "Production only", "Server-only", "never expose to browser"],
  ["DATABASE_URL", "Migration and server job database URL", "Production, CI", "Server-only", "postgresql://..."],
  ["EMAIL_PROVIDER_API_KEY", "Transactional email adapter", "Production", "Server-only", "provider key"],
  ["MPESA_CONSUMER_KEY", "M-Pesa adapter credential", "Production", "Server-only", "provider key"],
  ["MPESA_CONSUMER_SECRET", "M-Pesa adapter credential", "Production", "Server-only", "provider secret"],
  ["CARD_PROVIDER_SECRET_KEY", "Card checkout adapter credential", "Production", "Server-only", "provider secret"],
  ["ETIMS_PROVIDER_SECRET", "eTIMS adapter credential reference", "Production", "Server-only", "credential reference"],
  ["WEBHOOK_SIGNING_SECRET", "Webhook verification", "Production", "Server-only", "random secret"],
  ["CRON_SECRET", "Scheduled job authorization", "Production", "Server-only", "random secret"],
  ["ERROR_MONITORING_DSN", "Error monitoring provider", "Production", "Server-only", "dsn"],
  ["SUPPORT_EMAIL", "Support contact shown to tenants", "All", "Public", "support@example.com"],
  ["PLATFORM_ADMIN_ALLOWLIST", "Initial platform-admin bootstrap allowlist", "Production", "Server-only", "admin@example.com"],
];

export const launchChecklist = [
  "Production domain and SSL verified",
  "DNS configured",
  "Environment variables loaded",
  "Database migrations applied",
  "RLS verification completed",
  "Production seed excludes demo tenants",
  "Storage policies reviewed",
  "Auth redirect URLs configured",
  "Email domain verified",
  "Payment credentials configured",
  "Payment webhooks verified",
  "eTIMS environment confirmed",
  "Error monitoring connected",
  "Analytics configured",
  "Backups and restore drill completed",
  "Cron jobs configured",
  "Queue worker configured",
  "Platform admin accounts enrolled with MFA",
  "Legal pages reviewed and published",
  "Support contact live",
  "Pricing approved",
  "Subscription plans active",
  "Trial settings active",
  "Status page foundation ready",
  "Smoke tests complete",
  "Rollback plan rehearsed",
];

export const pilotChecklist = [
  "Pilot plan assigned",
  "Feature overrides reviewed",
  "Dedicated onboarding contact assigned",
  "Migration status tracked",
  "Training status tracked",
  "Go-live date agreed",
  "Support priority configured",
  "Feedback tracking enabled",
  "Known limitations documented",
  "Success metrics agreed",
  "Pilot completion status tracked",
];

export const launchReadinessReport = {
  classification: classifyLaunchReadiness(launchReadinessAreas),
  areas: launchReadinessAreas,
};
